modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mixins]]
config="trinkets.mixins.json"

[[mixins]]
config="trinkets-neoforge.mixins.json"

[[mods]]
modId = "trinkets"
version = "${version}"
displayName = "Trinkets"
authors = "Emi"
description = '''
Adds a data-driven accessory system to Minecraft
'''
logoFile = "icon.png"

[[dependencies.emi]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.72-beta,)" # network refactor
ordering="NONE"
side="BOTH"